### ISSUE TITLE
Register the Doc Up Component

### ISSUE THREAD

**Issue by taminachen** [mattermost/mattermost-plugin-docup#20]
How is the PostID obtained when registering the Doc up component?

**Comment by jwilander** [comment]
It's passed as an argument to any functions registered with `registerPostDropdownMenuAction `. It's used [here](https://github.com/mattermost/mattermost-plugin-docup/blob/master/webapp/src/index.js#L15) to fire off a redux action that both opens the modal and stores the post ID in state for the modal to retrieve as a prop

**Comment by taminachen** [comment]
thanks!
